spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usermicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Users-Service
server:
  port: 9090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true