server:
  port: 9092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordermicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true