spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productmicroservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Product-Service
server:
  port: 9091
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka
